### PR TITLE
Add transpile build step

### PR DESCRIPTION
**Pull request by jsg2021**
This library could be used more widely if it is transpiled.

I would like to use this fork of javascript-natural-sort because it's more current. But I need it transpiled. (I rather not run babel on things in the node_modules :))

### CODE REVIEW

**Comment by yobacca** [comment]
Good point!

But please consider https://mattandre.ws/2015/07/writing-npm-modules-es6-run-es5/. 

The /build/ directory should be added to the .gitignore file and a .npmignore file should be added which includes the same content like .gitignore except the /build/ directory.

I´d also prefer to rename the /js/ directory into /src/.

**Comment by jsg2021** [comment]
sure! :) I was just trying to minimize prescriptive changes. I can add those changes.

**Comment by yobacca** [comment]
Thanks! Last but not least the transpile task should be documented in the README.md. Please add the new default gulp task for transpilation to the "Development" section.
Cheers!

**Review by yobacca — APPROVED** [review]

**Comment by yobacca** [comment]
Thanks for your collaboration, Jonathan!

**Pull request merged**
